### ISSUE TITLE
Support new PHPCS array properties format

### ISSUE THREAD

**Issue by GaryJones** [m-e-h/theme-claim#3]
The current [regular expresions](https://github.com/m-e-h/theme-claim/blob/0060ad1e56bcaa489968ad8225bded8bf5e50675/lib/replace.js#L93) for array properties for `text_domain` and `prefixes` for PHPCS, don't support the new [array properties format](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.3.0), introduced in PHPCS 3.3.0.

The existing format is deprecated and will be removed in PHPCS 4.x, so folks who support PHP 5.4+ (which typically allows PHPCS 3.3+ unless there's a specific constraint set) are encouraged to switch to this new format.

**Comment by GaryJones** [comment]
Here's an example of a PHPCS config file that uses the new format for [prefixes](https://github.com/GaryJones/plugin-boilerplate/blob/7957db6a07dc95a22271563d001c828dcd68c634/.phpcs.xml.dist#L47) and [text domains](https://github.com/GaryJones/plugin-boilerplate/blob/7957db6a07dc95a22271563d001c828dcd68c634/.phpcs.xml.dist#L55).

**Comment by m-e-h** [comment]
Fixed in https://github.com/m-e-h/theme-claim/commit/ee305c90a5116dd7fdfaa7f84afca3b7a79cab25
This fix isn't perfect as it makes some assumptions about the order and number of array properties.

It does one find/replace for the "text_domain" `element-name` and one find/replace for the "prefixes" `element_name`, in that order, so single word theme names other than [Mythic](https://github.com/justintadlock/mythic) may get those replacements mixed up.

**Comment by GaryJones** [comment]
I think the regex could be improved to include the `element name=` bit as well, for the new format, while keeping the original regex for the old format.

Right now, if my theme name is `True`, `Parallel`, or `Array`, or any other attribute value from `package.json`, `phpcs.xml.dist`, `composer.json` et al, then the replacement of just the theme name in quotes, is going to catch far too much.

**Comment by m-e-h** [comment]
Right on @GaryJones 
Excellent points.
